#!/usr/bin/env node
// Build the single-file demo from modular sources in src/.
// Develop in src/{index.html,styles.css,app.js}; this inlines them into the one
// self-contained demo/agent-orchestration.html that the static host serves.
// CSS is minified; JS whitespace is minified but identifiers are NOT renamed,
// so the global functions/state that inline on* handlers depend on stay intact.
import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

const tmpl = read('src/index.html');
const css = (await esbuild.transform(read('src/styles.css'), { loader: 'css', minify: true })).code.trim();
// scenarios.js (data) is concatenated before app.js (logic) so COMPANY/SCENARIOS
// are defined first — they share one classic-script scope in the output.
const jsSource = read('src/scenarios.js') + '\n' + read('src/app.js');
const js = (await esbuild.transform(jsSource, {
  minifyWhitespace: true, minifySyntax: false, minifyIdentifiers: false,
  charset: 'utf8', // keep Korean/UTF-8 literals as-is instead of \u-escaping
})).code.trim();

const banner = '<!-- GENERATED by `npm run build` from src/. Edit src/{index.html,styles.css,app.js}, not this file. -->\n';
const out = banner + tmpl
  .replace('/*__CSS__*/', () => css)
  .replace('/*__APP_JS__*/', () => js);

if (out.includes('/*__CSS__*/') || out.includes('/*__APP_JS__*/')) {
  console.error('build: a marker was not replaced'); process.exit(1);
}
const outPath = path.join(root, 'demo/agent-orchestration.html');
fs.writeFileSync(outPath, out);
console.log(`built demo/agent-orchestration.html (${out.length} bytes; css ${css.length}, js ${js.length})`);
